#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# Fix Gnome Apps Slow  Start due to failing services
# Add this when you include flatpak in your system
#dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

pulseaudio &		# service for sound
mpd &			# music player daemon-you might prefer it as a service though
en &			# sets x english keyboard layout and runs remaps
#remaps &		# run the remaps script, switching caps/esc and more; check it for more info
setbg &		# set the background with the `setbg` script
#nitrogen --restore &	# restore background with nitrogen
#randomwal &
#xrdb ${XDG_CONFIG_HOME:-$HOME/.config/x11}/Xresources &	# Uncomment to use Xresources colors/settings on startup
#xcompmgr &		# xcompmgr for transparency
startpicom &
dunst &			# dunst for notifications
xset r rate 300 50 &	# Speed xrate up
unclutter &		# Remove mouse when idle
